const TEMPLATES = {
  cafe: {
    id: 'cafe',
    name: 'Cafe',
    description: 'Warm, cozy coffee shop with artisanal charm',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'centered' },
      { type: 'about', variant: 'split-right' },
      { type: 'services', variant: 'menu' },
      { type: 'gallery', variant: 'grid' },
      { type: 'testimonials', variant: 'carousel' },
      { type: 'faq', variant: 'compact' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'fade-up', card: 'stagger', hover: 'lift' },
    identity: {
      voice: 'warm',
      logoStyle: 'emblem',
      colorStrategy: 'earthy',
      spacing: 'generous',
      borderRadius: 'rounded',
      decorativeElements: ['blobs'],
    },
    typography: { heading: 'Playfair Display', body: 'Inter' },
  },
  restaurant: {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'Elegant fine dining with full-bleed visuals',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'fullscreen' },
      { type: 'about', variant: 'split-right' },
      { type: 'services', variant: 'grid-3' },
      { type: 'gallery', variant: 'masonry' },
      { type: 'testimonials', variant: 'single-featured' },
      { type: 'contact', variant: 'centered' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'parallax', card: 'scale-in', hover: 'glow' },
    identity: {
      voice: 'sophisticated',
      logoStyle: 'wordmark',
      colorStrategy: 'warm',
      spacing: 'generous',
      borderRadius: 'subtle',
      decorativeElements: ['lines'],
    },
    typography: { heading: 'Playfair Display', body: 'Lora' },
  },
  hotel: {
    id: 'hotel',
    name: 'Hotel',
    description: 'Luxury hospitality with sophisticated elegance',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'fullscreen' },
      { type: 'about', variant: 'split-left' },
      { type: 'services', variant: 'cards-hover' },
      { type: 'gallery', variant: 'grid' },
      { type: 'testimonials', variant: 'carousel' },
      { type: 'faq', variant: 'full' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'premium' },
    ],
    animations: { section: 'fade-up', card: 'stagger', hover: 'lift' },
    identity: {
      voice: 'luxurious',
      logoStyle: 'emblem',
      colorStrategy: 'gold',
      spacing: 'generous',
      borderRadius: 'subtle',
      decorativeElements: ['shapes'],
    },
    typography: { heading: 'Playfair Display', body: 'Lora' },
  },
  gym: {
    id: 'gym',
    name: 'Gym / Fitness',
    description: 'High-energy fitness with bold visuals',
    layout: [
      { type: 'navbar', variant: 'solid-dark' },
      { type: 'hero', variant: 'split' },
      { type: 'about', variant: 'stats-focused' },
      { type: 'services', variant: 'pricing' },
      { type: 'gallery', variant: 'grid' },
      { type: 'testimonials', variant: 'grid-2' },
      { type: 'faq', variant: 'compact' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'dark-compact' },
    ],
    animations: { section: 'slide-up', card: 'stagger', hover: 'scale' },
    identity: {
      voice: 'energetic',
      logoStyle: 'wordmark-bold',
      colorStrategy: 'vibrant',
      spacing: 'normal',
      borderRadius: 'sharp',
      decorativeElements: ['gradient-overlay'],
    },
    typography: { heading: 'Inter', body: 'Inter' },
  },
  salon: {
    id: 'salon',
    name: 'Salon / Spa',
    description: 'Soft, elegant beauty with luxurious treatments',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'minimal' },
      { type: 'about', variant: 'split-right' },
      { type: 'services', variant: 'card' },
      { type: 'gallery', variant: 'grid-2' },
      { type: 'testimonials', variant: 'carousel' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'fade-up', card: 'stagger', hover: 'lift' },
    identity: {
      voice: 'elegant',
      logoStyle: 'script',
      colorStrategy: 'pastel',
      spacing: 'generous',
      borderRadius: 'pill',
      decorativeElements: ['blobs'],
    },
    typography: { heading: 'Playfair Display', body: 'Inter' },
  },
  hospital: {
    id: 'hospital',
    name: 'Hospital',
    description: 'Trusted healthcare with professional clarity',
    layout: [
      { type: 'navbar', variant: 'solid-light' },
      { type: 'hero', variant: 'left-image' },
      { type: 'about', variant: 'split-left' },
      { type: 'services', variant: 'grid-3' },
      { type: 'gallery', variant: 'grid' },
      { type: 'testimonials', variant: 'grid-2' },
      { type: 'faq', variant: 'full' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'fade-up', card: 'stagger', hover: 'shadow' },
    identity: {
      voice: 'professional',
      logoStyle: 'wordmark',
      colorStrategy: 'cool',
      spacing: 'normal',
      borderRadius: 'subtle',
      decorativeElements: ['none'],
    },
    typography: { heading: 'Inter', body: 'Inter' },
  },
  clinic: {
    id: 'clinic',
    name: 'Clinic',
    description: 'Warm, approachable healthcare with personal touch',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'left-image' },
      { type: 'about', variant: 'split-right' },
      { type: 'services', variant: 'list' },
      { type: 'testimonials', variant: 'carousel' },
      { type: 'faq', variant: 'compact' },
      { type: 'contact', variant: 'centered' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'fade-up', card: 'stagger', hover: 'shadow' },
    identity: {
      voice: 'caring',
      logoStyle: 'wordmark',
      colorStrategy: 'soft-blue',
      spacing: 'generous',
      borderRadius: 'rounded',
      decorativeElements: ['blobs'],
    },
    typography: { heading: 'Inter', body: 'Inter' },
  },
  'law-firm': {
    id: 'law-firm',
    name: 'Law Firm',
    description: 'Authoritative legal services with classic design',
    layout: [
      { type: 'navbar', variant: 'solid-light' },
      { type: 'hero', variant: 'minimal' },
      { type: 'about', variant: 'split-right' },
      { type: 'services', variant: 'list' },
      { type: 'testimonials', variant: 'grid-2' },
      { type: 'faq', variant: 'full' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'fade-up', card: 'stagger', hover: 'shadow' },
    identity: {
      voice: 'authoritative',
      logoStyle: 'wordmark',
      colorStrategy: 'navy',
      spacing: 'normal',
      borderRadius: 'sharp',
      decorativeElements: ['lines'],
    },
    typography: { heading: 'Playfair Display', body: 'Inter' },
  },
  construction: {
    id: 'construction',
    name: 'Construction',
    description: 'Solid, trustworthy building with project showcase',
    layout: [
      { type: 'navbar', variant: 'solid-dark' },
      { type: 'hero', variant: 'split' },
      { type: 'about', variant: 'stats-focused' },
      { type: 'services', variant: 'grid-3' },
      { type: 'gallery', variant: 'masonry' },
      { type: 'testimonials', variant: 'grid-2' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'dark-compact' },
    ],
    animations: { section: 'slide-up', card: 'stagger', hover: 'shadow' },
    identity: {
      voice: 'trustworthy',
      logoStyle: 'wordmark-bold',
      colorStrategy: 'earthy',
      spacing: 'normal',
      borderRadius: 'sharp',
      decorativeElements: ['shapes'],
    },
    typography: { heading: 'Inter', body: 'Inter' },
  },
  'real-estate': {
    id: 'real-estate',
    name: 'Real Estate',
    description: 'Professional property showcase with market insight',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'fullscreen' },
      { type: 'about', variant: 'split-right' },
      { type: 'services', variant: 'grid-3' },
      { type: 'gallery', variant: 'showcase' },
      { type: 'testimonials', variant: 'carousel' },
      { type: 'faq', variant: 'full' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'fade-up', card: 'stagger', hover: 'lift' },
    identity: {
      voice: 'professional',
      logoStyle: 'wordmark',
      colorStrategy: 'cool',
      spacing: 'generous',
      borderRadius: 'subtle',
      decorativeElements: ['shapes'],
    },
    typography: { heading: 'Inter', body: 'Inter' },
  },
  photographer: {
    id: 'photographer',
    name: 'Photographer',
    description: 'Artistic portfolio with full-bleed imagery',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'fullscreen' },
      { type: 'about', variant: 'story-telling' },
      { type: 'services', variant: 'grid-3' },
      { type: 'gallery', variant: 'masonry' },
      { type: 'testimonials', variant: 'carousel' },
      { type: 'contact', variant: 'minimal' },
      { type: 'footer', variant: 'minimal' },
    ],
    animations: { section: 'parallax', card: 'scale-in', hover: 'scale' },
    identity: {
      voice: 'artistic',
      logoStyle: 'minimal',
      colorStrategy: 'monochrome',
      spacing: 'generous',
      borderRadius: 'sharp',
      decorativeElements: ['none'],
    },
    typography: { heading: 'Inter', body: 'Inter' },
  },
  'travel-agency': {
    id: 'travel-agency',
    name: 'Travel Agency',
    description: 'Vibrant destination showcase with wanderlust vibe',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'fullscreen' },
      { type: 'about', variant: 'split-right' },
      { type: 'services', variant: 'cards-hover' },
      { type: 'gallery', variant: 'grid' },
      { type: 'testimonials', variant: 'carousel' },
      { type: 'faq', variant: 'full' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'slide-up', card: 'stagger', hover: 'lift' },
    identity: {
      voice: 'adventurous',
      logoStyle: 'wordmark',
      colorStrategy: 'vibrant',
      spacing: 'generous',
      borderRadius: 'rounded',
      decorativeElements: ['blobs'],
    },
    typography: { heading: 'DM Sans', body: 'Inter' },
  },
  school: {
    id: 'school',
    name: 'School',
    description: 'Bright, nurturing educational environment',
    layout: [
      { type: 'navbar', variant: 'solid-light' },
      { type: 'hero', variant: 'centered' },
      { type: 'about', variant: 'split-left' },
      { type: 'services', variant: 'grid-4' },
      { type: 'gallery', variant: 'grid' },
      { type: 'testimonials', variant: 'grid-2' },
      { type: 'faq', variant: 'full' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'fade-up', card: 'stagger', hover: 'lift' },
    identity: {
      voice: 'nurturing',
      logoStyle: 'emblem',
      colorStrategy: 'bright',
      spacing: 'generous',
      borderRadius: 'rounded',
      decorativeElements: ['shapes'],
    },
    typography: { heading: 'DM Sans', body: 'Inter' },
  },
  'coaching-institute': {
    id: 'coaching-institute',
    name: 'Coaching Institute',
    description: 'Bold, results-driven education with modern design',
    layout: [
      { type: 'navbar', variant: 'solid-dark' },
      { type: 'hero', variant: 'split' },
      { type: 'about', variant: 'stats-focused' },
      { type: 'services', variant: 'pricing' },
      { type: 'gallery', variant: 'grid' },
      { type: 'testimonials', variant: 'grid-3' },
      { type: 'faq', variant: 'full' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'dark-compact' },
    ],
    animations: { section: 'slide-up', card: 'stagger', hover: 'scale' },
    identity: {
      voice: 'motivational',
      logoStyle: 'wordmark-bold',
      colorStrategy: 'gradient-heavy',
      spacing: 'normal',
      borderRadius: 'subtle',
      decorativeElements: ['gradient-overlay'],
    },
    typography: { heading: 'Inter', body: 'Inter' },
  },
  'digital-agency': {
    id: 'digital-agency',
    name: 'Digital Agency',
    description: 'Modern, tech-forward creative agency with impact',
    layout: [
      { type: 'navbar', variant: 'transparent' },
      { type: 'hero', variant: 'split' },
      { type: 'about', variant: 'split-right' },
      { type: 'services', variant: 'grid-3' },
      { type: 'gallery', variant: 'showcase' },
      { type: 'testimonials', variant: 'carousel' },
      { type: 'faq', variant: 'full' },
      { type: 'contact', variant: 'split' },
      { type: 'footer', variant: 'columns' },
    ],
    animations: { section: 'parallax', card: 'stagger', hover: 'glow' },
    identity: {
      voice: 'innovative',
      logoStyle: 'minimal',
      colorStrategy: 'bold-accent',
      spacing: 'generous',
      borderRadius: 'subtle',
      decorativeElements: ['shapes', 'gradient-overlay'],
    },
    typography: { heading: 'Inter', body: 'Inter' },
  },
};

export const SECTION_ANIMATIONS = {
  'fade-up': {
    initial: { opacity: 0, y: 60 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, margin: '-80px' },
    transition: { duration: 0.7, ease: [0.16, 1, 0.3, 1] },
  },
  'slide-up': {
    initial: { opacity: 0, y: 80 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, margin: '-60px' },
    transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] },
  },
  'parallax': {
    initial: { opacity: 0, y: 40 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, margin: '-100px' },
    transition: { duration: 0.8, ease: [0.12, 0, 0.39, 0] },
  },
  'fade-in': {
    initial: { opacity: 0 },
    whileInView: { opacity: 1 },
    viewport: { once: true, margin: '-50px' },
    transition: { duration: 0.8, ease: 'easeOut' },
  },
  'scale-in': {
    initial: { opacity: 0, scale: 0.95 },
    whileInView: { opacity: 1, scale: 1 },
    viewport: { once: true, margin: '-50px' },
    transition: { duration: 0.6, ease: [0.16, 1, 0.3, 1] },
  },
};

export const CARD_ANIMATIONS = {
  stagger: {
    hidden: { opacity: 0, y: 30 },
    visible: (i) => ({
      opacity: 1, y: 0,
      transition: { delay: i * 0.08, duration: 0.5, ease: [0.16, 1, 0.3, 1] },
    }),
  },
  'scale-in': {
    hidden: { opacity: 0, scale: 0.9 },
    visible: (i) => ({
      opacity: 1, scale: 1,
      transition: { delay: i * 0.06, duration: 0.5, ease: [0.16, 1, 0.3, 1] },
    }),
  },
};

export const HOVER_ANIMATIONS = {
  lift: { whileHover: { y: -4 } },
  scale: { whileHover: { scale: 1.03 } },
  shadow: { whileHover: { y: -2 } },
  glow: { whileHover: { y: -2 } },
  none: {},
};

export function getTemplate(id) {
  return TEMPLATES[id] || TEMPLATES['digital-agency'];
}

export default TEMPLATES;
